### ISSUE TITLE
Pricing

### ISSUE THREAD

**Issue by tathagatbanerjee** [q6a/website-2022#10]
### Task 1

* For pricing, we need it to look like below.

<img width="768" alt="Screen Shot 2022-11-21 at 9 31 18 am" src="https://user-images.githubusercontent.com/79488010/202950717-cace5b08-26e9-4152-9c64-a39783bbce1e.png">

* Future design, if changed to subscription-based model:

![image](https://user-images.githubusercontent.com/11780602/178906130-37877cd2-ea7d-4051-ba6a-8e4920a78530.png)

![image](https://user-images.githubusercontent.com/11780602/178906151-f8594b1a-523a-4344-86d6-f384853cdbd3.png)

- [x] Done

**Comment by yasintze** [comment]
For now, I'll ignore future design, we can continue in the next iteration

**Comment by yasintze** [comment]
@tessajoana please have a look at [here](https://deploy-preview-24--q6a-website-dev.netlify.app/pricing/)
