### ISSUE TITLE
Changes request (19/12/2022)

### ISSUE THREAD

**Issue by tessajoana** [q6a/website-2022#18]
- [x] 1. Please change the text position to center align for the words "Transcribe, translate and dub videos in few sample steps. Try it now. No account required!"

<img width="1164" alt="Screenshot 2022-12-19 at 11 27 41 am" src="https://user-images.githubusercontent.com/79488010/208327651-ba7a13cc-f7a5-40d4-85df-7a314c38b9f1.png">

- [x] 2. Please add a rounded corner box for the 'your partner in video marketing' part, similar to the screenshot below and make it smaller. The idea is that users can see the editor demo when they get on the landing page and be prompted to scroll down.

<img width="810" alt="Screenshot 2022-12-19 at 11 33 52 am" src="https://user-images.githubusercontent.com/79488010/208327825-e87282f4-a9b3-4baa-803c-b63f1d539b1b.png">

- [x] 3. Move the 'transcribe and translate' tab on top of the video but under the 'try our editor demo' text.

- [x] 4. Can you please make the photo frame touch the edge of the rounded box? I want to see how it looks.

<img width="1106" alt="Screenshot 2022-12-19 at 11 36 01 am" src="https://user-images.githubusercontent.com/79488010/208327977-e9f85448-3ece-4890-b2b9-014a474055e9.png">

- [x] 5. Can you please move the language and help boxes on where the x's are marked so they are aligned with the rounded boxes? 

![x](https://user-images.githubusercontent.com/79488010/208563934-fb97130f-6918-411e-84e6-a88f554d1011.jpg)

**Comment by yasintze** [comment]
@tessajoana I made a few changes according to your request, please take a look [https://63a06ae43c221600080d4f1a--q6a-website-dev.netlify.app/](https://63a06ae43c221600080d4f1a--q6a-website-dev.netlify.app/), and let me know what you think

Before I create PR, I want to ask some questions

-  Based on point 1 -- May I know what is your reason to put the text align in the hero section to the center? if you take a look at other websites, they usually set the text-align to the left if the section contains text and images in one row. I'm not UI/UX specialist, but I believe they have their own reason to have this
![ref-1](https://user-images.githubusercontent.com/21036432/208441697-88e208e3-ceca-4a2a-8cff-38b4b71181a6.png)
![ref-2](https://user-images.githubusercontent.com/21036432/208441749-ea5fbb4e-f57f-4fd4-9a9a-d819f1311159.png)
![ref-3](https://user-images.githubusercontent.com/21036432/208441773-a400dce2-6455-4ce2-b18d-d063fe48b4b7.png)
![ref-4](https://user-images.githubusercontent.com/21036432/208441812-77dafdb9-cd52-41b7-870e-42e280683cb0.png)

- Based on point 2 -- In my opinion, it's better if there's no spacing and no rounded on hero section, but sure I'm open if you have another opinion

**Comment by tessajoana** [comment]
@yasintze thank you for your quick update. 

In terms of point 1, I agree with you - it does look better with the left justification. I think what's missing is a full stop after "...few simple steps.". Also, the word simple was misspelled (sample instead of simple). 

<img width="1331" alt="Screenshot 2022-12-20 at 12 56 27 pm" src="https://user-images.githubusercontent.com/79488010/208563653-ed21cac6-180f-4c6a-9f8d-fe69755ab5c9.png">

For point 2, I want the demo section to look like the Rev screenshot you added. There, users get to see the pricing on the landing page. For me, it prompted me to scroll down and find out more information about the product. Hence why I wanted the spacing.

I have also added 1 more point to the issue above.

Thank you so much Yasin :)

**Comment by yasintze** [comment]
@tessajoana please have a look at the updates here https://vt-001--q6a-website-dev.netlify.app/

@tathagatbanerjee please have a look at the following PR https://github.com/q6a/website-2022/pull/19

thank you so much :)
