### ISSUE TITLE
Website Structure Requirement

### ISSUE THREAD

**Issue by tathagatbanerjee** [q6a/website-2022#2]
### Task 1

The structure of the website should be as below. 

1. Index (Home)
2. About Us (About)
3. Contact Us
4. Privacy Policy
5. Terms And Conditions
6. Sitemap
7. Frequently Asked Questions (Learn)
8. Available Languages
10. Pricing (Pricing)
11. News

All these need to include a **Google Analytics tracker** so we can track what people are clicking.

Full wireframe: 

[Website landing page wireframe Nov 22.pdf](https://github.com/q6a/website-2022/files/10039001/Website.landing.page.wireframe.Nov.22.pdf)

Please note that there are some pages created in this wireframe that we won't be making at the moment. Eg feature request, roadmap, careers, etc.

- [x] Done

### Task 2 

The header looks like below.

<img width="771" alt="Screen Shot 2022-11-18 at 2 10 26 pm" src="https://user-images.githubusercontent.com/79488010/202642757-f0924af6-98d1-4401-b1b0-35f8c427bdcf.png">

* You can see the Home, About, Learn and Pricing toggles, which should become the above. 
* Home - this is the main index page.
* About - Drop down for About Us, Contact Us, Privacy Policy, T&C, and sitemap.
* Learn - Drop down for FAQ's, Available Languages and Blog.
* Pricing - Drop down for Pricing.

Please also mockup Help. 

Note, below is image of app once user logs in or signs in. Don't worry about the templates and features, they are not in the roadmap yet, but you can see how it should work once the user logs in. _This is only for FYI._

![image](https://user-images.githubusercontent.com/11780602/178640474-873835fe-8d62-4682-8489-9c8a85b72d60.png)

- [ ] Done 

### Task 3

The structure of the website should be such that we have a global page at https://videotranslator.ai/ which looks like below.

![image](https://user-images.githubusercontent.com/11780602/178640676-e1137977-d047-4010-90fb-21145eaefea9.png)

* Practically, the main website will be at https://videotranslator.ai/en/ etc etc.

- [ ] Done

**Comment by yasintze** [comment]
@tessajoana @tathagatbanerjee according to i18n best practice, the default languages will have no prefix e.g. `/en`, because for some reasons such as not ideal for SEO, too many redirects, etc. Please see [here](https://github.com/vercel/next.js/discussions/18419)
