### ISSUE TITLE
Blog: Enhancements

### ISSUE THREAD

**Issue by tessajoana** [q6a/website-2022#28]
These are the enhancements required based on the current version of Strapi CRM. Written on 16 March 2023.

- [x] 1. When I sort it into oldest-newest, can it please show on display? Currently, it still shows 'sort by'.

https://user-images.githubusercontent.com/79488010/225162238-204033a7-b891-402a-8dd2-b4adf810642f.mov

- [x] 2. Add dates.
The title 'Social Media Guide To Video 2' shows up as the oldest blog when I sorted it out. However, I couldn't see any date edits in Strapi. How do I edit this? For example, this is how the calendar edit looks from Forestry.

<img width="492" alt="Screenshot 2023-03-15 at 7 16 04 am" src="https://user-images.githubusercontent.com/79488010/225164729-c0d98f26-d85f-47e4-8e46-e53bdd97f3e8.png">

and then, can you add the date on the website as well please? Just like the below.

<img width="953" alt="Screenshot 2023-03-15 at 7 36 09 am" src="https://user-images.githubusercontent.com/79488010/225165581-3720133f-3aae-4639-b636-b7dc8f7e8149.png">

And under the title of the blog post. Don't worry about adding the text, "last updated on". Just make it show the date originally set in the 'calendar'.

<img width="953" alt="Screenshot 2023-03-15 at 7 36 20 am" src="https://user-images.githubusercontent.com/79488010/225165637-1e718c45-fc0e-4920-af65-16a854557342.png">

- [ ] 3. For the blog editor in Strapi, is it possible to make it in vertical format? 1 column for the information and 1 column for the text edit, just like this example.

<img width="1198" alt="Screenshot 2023-03-15 at 7 31 07 am" src="https://user-images.githubusercontent.com/79488010/225164946-a0d729f3-2bd8-4e3e-b476-dcb5ae98f247.png">

- [x] 4. For keywords, is there a way to make them look like the below? The `"text",` format is kind of annoying to do for every post.

<img width="345" alt="Screenshot 2023-03-15 at 7 32 39 am" src="https://user-images.githubusercontent.com/79488010/225165189-a610b409-29e4-48fe-8956-2a984dbe4a2b.png">

Here is an example from Forestry. Here, I just have to add the text in the box provided and click enter. I do not have to keep adding `"`, write my text, and finish off with another `",`.

https://user-images.githubusercontent.com/79488010/225476603-2b4700fe-934b-468c-8cc5-6d80bf93f903.mov

**Comment by yasintze** [comment]
@tessajoana some replies refer to comment number

3. I don't think this can be implemented on Strapi
4. There are 2 possible approaches to handle this with Strapi

a. Create new collection types with the name "Blog Keywords", and before you add to Blog, you have to input the keywords one by one inside Blog Keywords, similar to "Blog Category", and "Blog Tag"
b. Input the keywords to current fields using comma separated, e.g. `this is a test keyword, what are the disadvantages of tr, ... etc.`

What do you think?

**Comment by tessajoana** [comment]
Hi Yasin, let me think first about comment no. 3. 

For comment no. 4, let's go with the comma-separated text instead. Thank you!

**Comment by yasintze** [comment]
Hi @tessajoana, here are some updates
- Show blog post sorted status (ascending or descending)
- Show posted date on blog posts
- Sort blog posts by `postedDate` column in Strapi

please have a look at [MR #29](https://github.com/q6a/website-2022/pull/29), and see deploy preview [here](https://vt-010--q6a-website-dev.netlify.app/blog/)
