### ISSUE TITLE
Blog post CMS

### ISSUE THREAD

**Issue by tessajoana** [q6a/website-2022#30]
- [x] 1. Does strapi have a rich field view similar to DatoCMS? 
- [x] 2. Can there be an image preview the moment I added the images on the blog post text edit. Currently, I have to constantly clicking on preview mode to check which image I have uploaded.
- [x] 3. Right now, whenever I add an image, it scrolls me back to the top of the blog post text edit. Is there a way to stop this because it is pretty annoying? 

https://user-images.githubusercontent.com/79488010/231059813-afae4cf4-5a6e-4118-ba73-a2a22a8697bf.mov

- [x] 4. How do I add YouTube links? Eg the blog post How VideoTranslatorAI Helps Multicultural Communities In Emergencies has a YouTube link. However, the actual video doesn't show up.
- [x] 5. Can you please add a date section in when I blog so I can filter by date? Eg latest or oldest.

**Comment by yasintze** [comment]
Hi @tessajoana, I have some updates for CMS and the websites. Please have a look at this [page](https://main--q6a-website-dev.netlify.app/blog/how-video-translator-ai-helps-multicultural-communities-in-emergencies/). I also replaced the Strapi's default markdown editor into a rich text editor, please have a look at the **CMS -> Content Manager -> Blog**

**Comment by tessajoana** [comment]
Hi @yasintze. Nice job :) I like the photo preview. 1 question: Is there a way to make the rich text box bigger? It is quite small right now. So when there is an image, it occupies the whole box. 

I have also checked the About Us page and it has updated.

Thank you!

**Comment by yasintze** [comment]
@tessajoana I think everything is done related to this issue, let me know if I missing something
