### ISSUE TITLE
New web/cms enhancements

### ISSUE THREAD

**Issue by tessajoana** [q6a/website-2022#33]
Hi Yasin, I have a couple of web/cms enhancement requests.

- [x] 1. Add meta description counter
Is it possible to add something like this in the blog description box?

<img width="750" alt="Screenshot 2023-05-16 at 12 56 43 pm" src="https://github.com/q6a/website-2022/assets/79488010/9bf5f4f0-26ba-44cc-8664-65ede8982547">

- [x] 2. Instead of load more, can you make the blog post load to different pages? Currently, if i have scrolled down with the load more button, click on a blog post and click back, it will load me back to the top blog post.

https://github.com/q6a/website-2022/assets/79488010/4a9912e6-93ee-4949-868d-26e3cf39fa5b

<img width="863" alt="Screenshot 2023-05-16 at 12 57 02 pm" src="https://github.com/q6a/website-2022/assets/79488010/0a995f4d-3d42-4dbf-8e98-e5755017c682">

- [x] 3. Auto save while editing blog post. I can accidentally close the tab or my computer can suddenly shut down whilst writing a blog post.

**Comment by yasintze** [comment]
@tessajoana I'll close this issue
