### ISSUE TITLE
Website fixes before going live

### ISSUE THREAD

**Issue by tessajoana** [q6a/website-2022#34]
Hi @yasintze, can you please do the following fixes?

- [x] 1. Fix the logo. This needs to be VideoTranslator's logo.

<img width="132" alt="Screenshot 2023-06-08 at 1 09 27 pm" src="https://github.com/q6a/website-2022/assets/79488010/8836e573-ef2b-47d2-8aad-b6a6188b9f0a">

- [x] 2. Change this to: "Read Our Blog..."

<img width="453" alt="Screenshot 2023-06-08 at 1 10 04 pm" src="https://github.com/q6a/website-2022/assets/79488010/4ee85d72-6590-441f-9cf2-e65870736af1">

- [x] 3. Change this to ‘Client Stories’. Also, ideally clicking on the name of the post or the image should also take a user to the article.

<img width="1286" alt="Screenshot 2023-06-08 at 1 11 27 pm" src="https://github.com/q6a/website-2022/assets/79488010/70904d28-4d8c-4745-b709-61277041f9b8">

- [x] 4. Our clients should be above our partners. Can we get logos of the below and add some more in please for clients? The idea is that there will be 6 but it moves. Something like this:

Uploading Screen Recording 2023-06-08 at 1.47.54 pm.mov…

- https://www.hearst.com/
- https://www.bureauvisueel.com/
- https://soulcitychurch.com/
- https://www.boxbike.com/
- https://dgblend.net/it/
- https://www.persistent.com/
- https://sustainableelectronics.org/
- https://www.ptc.com/
- https://www.creativetheorygroup.com/
- https://www.spiritofspace.com/
- https://www.innio.com/en
- https://ducodigital.com/
- http://crescolabs.com/
- http://majorminorproductions.com/
- http://iandg.com.au/
- https://www.boma.global/
- https://www.monaco-telecom.mc/
- https://www.retorio.com/
- https://www.simplify-europe.co.uk/?locale=en
- https://www.dawnfoods.com/

- [x] 5. Add contact us next to coming soon 

<img width="737" alt="Screenshot 2023-06-08 at 1 14 40 pm" src="https://github.com/q6a/website-2022/assets/79488010/3a3853b7-65ce-4570-9936-c03776bfd366">

- [x] 6. Change to: We have over 120 languages to choose from!

<img width="737" alt="Screenshot 2023-06-08 at 1 27 26 pm" src="https://github.com/q6a/website-2022/assets/79488010/1a0a9b40-eba9-4564-b0a5-4860be4a4592">

- [x] 7. Can you please make the displayed blog post 6? And then change "More blog post" to "More blogs".

<img width="1009" alt="Screenshot 2023-06-08 at 1 49 25 pm" src="https://github.com/q6a/website-2022/assets/79488010/b9a3b207-4a93-4516-b860-c4d397e050ba">

- [x] 8. Please make the language switch available even when you scroll all the way to the footer. Currently, it is only there until the case studies.

<img width="202" alt="Screenshot 2023-06-08 at 1 49 34 pm" src="https://github.com/q6a/website-2022/assets/79488010/e55ad582-e424-4245-b488-0165afd35fb1">

- [x] 9. Please change sample to simple.

![image](https://github.com/q6a/website-2022/assets/79488010/e8ec9af1-e832-437c-9bae-c9579ef95e1c)

**Comment by yasintze** [comment]
@tessajoana Some client links are inactive or have no logo, please have a look at the list below
- [majorminorproductions](https://majorminorproductions.com/) -> have no logo in their website
- [https://www.creativetheorygroup.com/](https://www.creativetheorygroup.com/) -> They are using a service from Wix.com and are currently inactive

**Comment by yasintze** [comment]
@tessajoana I can't see your uploaded screen record on task 4, but I try my best to imagine what you want. Please have a look at [https://q6a-website-dev.netlify.app/](https://q6a-website-dev.netlify.app/)

**Comment by tessajoana** [comment]
@yasintze in regards to the 2, just ignore them, it's fine. With task 4, it's pretty much what I envisioned. Nice work!

**Comment by yasintze** [comment]
@tessajoana cool, I'll close this issue
