### ISSUE TITLE
Contact Us Requirement

### ISSUE THREAD

**Issue by tathagatbanerjee** [q6a/website-2022#5]
### Task 1

* We need the contact us page to look like below. This is just a static form which sends us an email.

![image](https://user-images.githubusercontent.com/11780602/178894459-165bfe4c-325e-4fd6-a7f0-1176c14a224a.png)

- [x] Done

**Comment by yasintze** [comment]
@tessajoana @tathagatbanerjee  please have a look at the demo here https://vt-002--q6a-website-dev.netlify.app/contact/ currently sent to my email, but we can change it later

I'm using Netlify forms for sending email services, it has free 100 submissions per month 

Steps to reproduce:
- Open the given URL above
- Scroll to the footer and click `Contact Us`
- Fill out the form
- Submit
- Check here https://app.netlify.com/sites/q6a-website-dev/forms/63a452d9c58a6c0008d1911b

**Comment by tessajoana** [comment]
@yasintze looking good! I really like it.

 I have 2 comments regarding it, though:

1. Will there be a captcha button? Do you think this will be necessary for now or should we just add them later in the future?
2. I cannot click on the netlify link.

<img width="572" alt="Screenshot 2022-12-23 at 10 48 36 am" src="https://user-images.githubusercontent.com/79488010/209244159-b5af53e9-a88a-45dd-b04a-03cb6f89994c.png">

**Comment by yasintze** [comment]
@tessajoana email successfully sent to my email
<img width="950" alt="Screen Shot 2022-12-23 at 07 57 24" src="https://user-images.githubusercontent.com/21036432/209250189-a34afb2b-97e0-4509-b8d3-3cf630f5613f.png">

For the Recaptcha, the wireframe contains v2 (I am not a robot), but I recommend using v3 with better security, please create a new key and I'll add it to the contact form

**Comment by tessajoana** [comment]
@yasintze Hi Yasin, what do you mean by creating a new key? I have googled Recaptcha v3 but cannot see a notable look in the visuals. Is it just in the code?

**Comment by yasintze** [comment]
@tessajoana I mean a key for reCAPTCHA v3, please follow instruction [here](https://support.voipcloud.online/hc/en-us/articles/360001921175-Create-reCAPTCHA-v3-keys). The v3 is a bit different from the previous one, they verify requests with a score and without user interaction

**Comment by yasintze** [comment]
@tessajoana I think it's okay if you would like to use v2, then you can set the configuration settings in Recaptcha admin console to the most secure
