### ISSUE TITLE
Privacy Policy + Terms And Conditions

### ISSUE THREAD

**Issue by tathagatbanerjee** [q6a/website-2022#6]
### Task 1

* For privacy policy, we need something like the below.

![image](https://user-images.githubusercontent.com/11780602/178905244-e2d3174e-2b41-4df6-9b4d-635edf413140.png)

- [x] Done

### Task 2

* For terms and conditions we need something like the below.

![image](https://user-images.githubusercontent.com/11780602/178905316-9612c70a-294c-4df5-965a-12106800104d.png)

- [x] Done

**Comment by yasintze** [comment]
this code covered by the next PR (https://github.com/q6a/website-2022/pull/22)
