### ISSUE TITLE
FAQ's

### ISSUE THREAD

**Issue by tathagatbanerjee** [q6a/website-2022#8]
### Task 1

* For FAQs these need to be in different languages too.

![image](https://user-images.githubusercontent.com/11780602/178905578-a79c1139-7635-40b3-b48b-a428984a3b61.png)

![image](https://user-images.githubusercontent.com/11780602/178905598-947976bc-1095-4bf6-9166-a2ef6bf7acd9.png)

- [x] Done

**Comment by tessajoana** [comment]
Hi @yasintze , where can I see the mockup for the FAQs page?
